= Commands

== Clear anything running in your cluster

Here we assume that in k8s you have all the yamls you've created in the previous workshop run.

```
kubectl delete -f k8s/
```

== Download a simple project

```
$ curl https://start.spring.io/starter.tgz -d dependencies=actuator,web,cloud-starter -d language=java -d type=maven-project -d baseDir="spring-loves-k8s" -d artifactId="spring-loves-k8s" -d name="spring-loves-k8s" | tar -xzvf -
$ cd spring-loves-k8s/
$ cat > src/main/resources/application.properties <<EOL
management.endpoints.web.exposure.include=*
EOL
```

== Build boot image

```
$ ./mvnw -DskipTests spring-boot:build-image -Dspring-boot.build-image.imageName=docker.io/springcloud/spring-loves-k8s
```

== Push image

```
$ docker push springcloud/spring-loves-k8s
```

== Run image that simulates being run in Kubernetes

```
$ docker run -e KUBERNETES_SERVICE_HOST="bla" -e KUBERNETES_SERVICE_PORT=1234 -p 8080:8080 docker.io/springcloud/spring-loves-k8s
```

=== [OPTIONAL] Show k8s actuator endpoints

```
$ http :8080/actuator/health
$ http :8080/actuator/health/liveness
$ http :8080/actuator/health/readiness
```

== Point kubectl to proper namespace

```
$ kubectl create namespace spring-cloud
$ kubectl config set-context --current --namespace=spring-cloud
```

== Create a configmap for deployment (INFO LOGS)

```
$ kubectl create configmap log-level --from-literal=LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=INFO
```

== Print the config map yaml

We will show how to do it but for the demo let's just do the "Store the config map on drive" point

```
$ mkdir -p k8s
$ kubectl get configmap log-level -o yaml > k8s/config-map.yml
```

== Store the config map on drive

```
$ cat >./k8s/config-map.yml <<EOL
apiVersion: v1
data:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: INFO
kind: ConfigMap
metadata:
  labels:
    "spring.cloud.kubernetes.config": "true"
  name: log-level
  namespace: spring-cloud
EOL
$ kubectl apply -f ./k8s/config-map.yml
```

== Generate deployment

```
$ mkdir -p k8s && kubectl create deployment spring-loves-k8s --image docker.io/springcloud/spring-loves-k8s -o yaml --dry-run=client > k8s/deployment.yaml
```

=== Update yaml

```bash
$ cat >./k8s/deployment.yaml <<EOL
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-loves-k8s
  name: spring-loves-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-loves-k8s
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-loves-k8s
    spec:
      containers:
      - image: docker.io/springcloud/spring-loves-k8s
        name: spring-loves-k8s
        envFrom:
        - configMapRef:
            name: log-level
        resources: {}
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
status: {}
EOL
```

== Generate service

```
$ kubectl create service clusterip spring-loves-k8s --tcp 80:8080 -o yaml --dry-run=client > k8s/service.yaml
```

=== Update

```
$ cat >./k8s/service.yaml <<EOL
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-loves-k8s
  name: spring-loves-k8s
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-loves-k8s
  type: LoadBalancer
status:
  loadBalancer: {}
EOL
```

== (OPTIONAL) Update service type to LoadBalancer for external IP

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-loves-k8s
  name: spring-loves-k8s
  namespace: spring-cloud
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-loves-k8s
  type: ClusterIP
status:
  loadBalancer: {}
```

== Apply changes to the kubernetes cluster

```
$ kubectl apply -f ./k8s
```

== Open port 80 to the public

```
$ kubectl get services --namespace=spring-cloud
$ kubectl port-forward service/spring-loves-k8s 8080:80
```

== Show k8s actuator endpoints

```

$ http :8080/actuator/health
$ http :8080/actuator/health/liveness
$ http :8080/actuator/health/readiness
```

== Show logs with INFO only

```
$ kubectl get pods
# we get the pod name e.g. [spring-loves-k8s-64cc4dd87c-qvv7b]
$ kubectl logs spring-loves-k8s-64cc4dd87c-qvv7b
```


== (Optional) Attach the config map to the container

This should already be done.

```yml
containers:
- image: docker.io/springcloud/spring-loves-k8s
    name: spring-loves-k8s
    envFrom:
        - configMapRef:
            name: log-level
```

== (Optional) Redeploy

```
$ kubectl apply -f ./k8s
```

== Restart (if not taking optional step)

```
$ kubectl scale --replicas=0 -f k8s/deployment.yaml
$ kubectl scale --replicas=1 -f k8s/deployment.yaml
```

== Show logs with DEBUG too

```
$ kubectl get pods
# we get the pod name e.g. [spring-loves-k8s-64cc4dd87c-qvv7b]
$ kubectl logs spring-loves-k8s-64cc4dd87c-qvv7b
```

== Create roles for the config watcher

```bash
$ cat > ./k8s/roles.yml << EOL
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: spring-cloud
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: spring-cloud
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
EOL
$ kubectl apply -f ./k8s/roles.yml
```

== Apply config-watcher.yml

https://hub.docker.com/r/springcloud/spring-cloud-kubernetes-configuration-watcher

```bash
$ cat >./k8s/config-watcher.yml <<EOL
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
      name: spring-cloud-kubernetes-configuration-watcher
    spec:
      ports:
        - name: http
          port: 8888
          targetPort: 8888
      selector:
        app: spring-cloud-kubernetes-configuration-watcher
      type: ClusterIP
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
      name: spring-cloud-kubernetes-configuration-watcher
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      labels:
        app: spring-cloud-kubernetes-configuration-watcher
      name: spring-cloud-kubernetes-configuration-watcher:view
    roleRef:
      kind: Role
      apiGroup: rbac.authorization.k8s.io
      name: namespace-reader
    subjects:
      - kind: ServiceAccount
        name: spring-cloud-kubernetes-configuration-watcher
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      namespace: default
      name: namespace-reader
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
        verbs: ["get", "list", "watch"]
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: spring-cloud-kubernetes-configuration-watcher-deployment
    spec:
      selector:
        matchLabels:
          app: spring-cloud-kubernetes-configuration-watcher
      template:
        metadata:
          labels:
            app: spring-cloud-kubernetes-configuration-watcher
        spec:
          serviceAccount: spring-cloud-kubernetes-configuration-watcher
          containers:
            - name: spring-cloud-kubernetes-configuration-watcher
              image: springcloud/spring-cloud-kubernetes-configuration-watcher:2.0.2
              imagePullPolicy: IfNotPresent
              readinessProbe:
                httpGet:
                  port: 8888
                  path: /actuator/health/readiness
              livenessProbe:
                httpGet:
                  port: 8888
                  path: /actuator/health/liveness
              ports:
                - containerPort: 8888
EOL
$ kubectl apply -f ./k8s/config-watcher.yml
```

== Follow the logs

```bash
$ kubectl logs spring-loves-k8s-64cc4dd87c-qvv7b --follow
```

== We change the config map entry back to DEBUG

```
$ cat >./k8s/config-map.yml <<EOL
apiVersion: v1
data:
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK: DEBUG
kind: ConfigMap
metadata:
  labels:
    "spring.cloud.kubernetes.config": "true"
  name: log-level
  namespace: spring-cloud
EOL
$ kubectl apply -f ./k8s/config-map.yml
```

Now we should see the difference!
